site_name: Game-Docs
site_url: https://game-docs.com/
nav:
  - Home: index.md
  - Features: features.md
  - Scripts: scripts.md
  - Beautification: beautification.md
  - Creative Package: creativepackage.md
theme: cinder

